version: 0.2

phases:
  install:
    commands:
      - echo current node version `node --version`
      - npm install -g yarn lerna serverless
   pre_build:
    commands:
      - echo Bootstrap source code
      - yarn install
      - lerna bootstrap
      - yarn run test
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
