version: 0.2

phases:
  install:
    commands:
      - echo current node version `node --version`
      - echo Installing yarn
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt-get -y update
      - apt-get install -y yarn
      - echo Installing global dependencies
      - yarn global add lerna serverless
   pre_build:
    commands:
      - echo Bootstrap source code
      - yarn
      - lerna bootstrap
      - yarn run test
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
