version: 0.2

phases:
  install:
    commands:
      - ls -lha
      - echo current node version `node --version`
      - echo Installing system packages
      - echo Installing global dependencies
      - npm install -g yarn
      - yarn global add lerna serverless
   pre_build:
    commands:
      - echo Bootstrap source code
      - yarn
      - lerna bootstrap
      - yarn run test
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`    
