service: execution-context-reuse

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
